version: '3.9'

services:
  member:
    image: member-api:latest
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile-local
    ports:
      - "3001:8001"
    environment:
      - PORT=8001
      - NODE_ENV=local
    restart: always
    networks:
      - msa-api-network

networks:
  msa-api-network: