# 기본 이미지 설정
FROM node:18

# 작업 디렉토리 생성
WORKDIR /usr/src/app

# 의존성 설치
COPY package.json ./
RUN npm install

# 소스 코드 복사
COPY . .

# 앱 빌드
RUN npm run build
#RUN npm run start:debug

# 앱을 실행할 사용자 생성
RUN groupadd -r nestjs && useradd -r -g nestjs nestjs
RUN chown -R nestjs:nestjs /usr/src/app

# 사용자를 변경하여 앱 실행
USER nestjs

# 컨테이너 실행 시 실행될 명령어 설정
CMD ["npm", "run", "start:debug"]